### PR TITLE
Fix card details

### PR DESCRIPTION
**Pull request by kojiadrianojr**
image

### CODE REVIEW

**Review by harveyjavier — APPROVED** [review]
Fixed!

**Comment by kojiadrianojr** [comment]
launchcard-details

**Comment by harveyjavier** [comment]
uyan na! 🚀

**Review by kbaldo — APPROVED** [review]
Looks great!

**Review by mativanarquero — APPROVED** [review]

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Comment by mativanarquero** [comment]
AGITH!
*practice lang po

**Pull request merged**
