### PR TITLE
Modify components

### PR DESCRIPTION
**Pull request by kojiadrianojr**
Resolve issue #14 
issues
Resolves issue #27 
issues2

### CODE REVIEW

**Comment by swengr-janan** [comment]
@kojiadrianojr  mali ata yung na reference mo sa issue sa first item

**Comment by kojiadrianojr** [comment]
> @kojiadrianojr mali ata yung na reference mo sa issue sa first item

di ko nakita na may suggest ka palan na design

**Comment by kojiadrianojr** [comment]
image

**Comment by swengr-janan** [comment]
Ahhh. Ya. Mas maganda yung gawa mo. Mock up man lang yung sakin. Di kasi nakita sa GIF haha. Anyways, looks good to me.

**Comment by kojiadrianojr** [comment]
eto original kuys 
image

**Comment by kojiadrianojr** [comment]
> Ahhh. Ya. Mas maganda yung gawa mo. Mock up man lang yung sakin. Di kasi nakita sa GIF haha. Anyways, looks good to me.

ah oks oks thanks kuys

**Comment by kojiadrianojr** [comment]
makas kason kaya su gif anep hahaha @swengr-janan

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
