### PR TITLE
Make data dynamic in pages

### PR DESCRIPTION
**Pull request by medardm**

### CODE REVIEW

**Review by mativanarquero — APPROVED** [review]
LGTM

**Review by kojiadrianojr — APPROVED** [review]
GNYP

**Review by Pseudoman21 — APPROVED** [review]
Flexible!

**Review by harveyjavier — APPROVED** [review]
Zestful!

**Review by swengr-janan — APPROVED** [review]
LGTB!

**Review by aldrickb — APPROVED** [review]
LGTTM

**Pull request merged**
