### PR TITLE
Update headers and resolve issues

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Fix disappearing 'Enter SparkLaunch' button and mobile responsiveness on lower resolutions
      - * components' mobile responsiveness WIP
- [x] Add background image for project headers
- [x] Update header and card background image for Ownly
- [x] Add period - 'confirm transaction.' for withdraw modal component
 
styledlink button
proj_headers
ownly_bg

### CODE REVIEW

**Review by kojiadrianojr — APPROVED** [review]
Updatified!

**Review by Pseudoman21 — APPROVED** [review]
Ahead!

**Comment by swengr-janan** [comment]
Yung mga text sa icons mat, how do they look kapag smaller screens?

**Comment by mativanarquero** [comment]
> Yung mga text sa icons mat, how do they look kapag smaller screens?

Icons' size itself remains static for now po sir.

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
