### PR TITLE
Update Round 2 - FCFS

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Integrate light and dark mode images for Round 2 - FCFS
    - Update round 2 - FCFS image
    - Instantiate light mode icon to RenderRoundTwo 
    - Remove and delete temporary round 2 - FCFS images
round2_light_dark
round2_mobile
round2_mobile_light

### CODE REVIEW

**Review by harveyjavier — APPROVED** [review]
Fight! 🥊

**Review by Pseudoman21 — APPROVED** [review]
Enlightened!

**Comment by swengr-janan** [comment]
Mat, kamusta to sa mobile version?

**Comment by swengr-janan** [comment]
Upload ka nalang ulit Mat ng LICEcap gif para sa mobile version or kahit image lang.

**Comment by mativanarquero** [comment]
> Mat, kamusta to sa mobile version?

Mobile views:
round2_mobile
round2_mobile_light

**Comment by swengr-janan** [comment]
Nice one!

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
