### PR TITLE
UI Updates

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Add and integrate animation to home header
	- Add function for animated svgs
	- Create container for header animation
	- Add animated svgs to ./images
- [x] Create animation container and update header formatting
	- Update styled heading formatting
	- Update Home formatting and add responsive support for desktop and mobile resolutions
	- Add and isolate style for header - two column wrapper
	- Update content justifications for 1920px, 1366px, and lower than 500px mobile resolutions
	- Reverse header column grid order when resolution is less than 1000px
- [x] Render round 2 - FCFS image and details
	- Add temporary round 2 FCFS image
	- Allow image scaling on lower resolutions and update container padding
	- Add Round 1- Allocation round to tiered system container
	- Update Header title formatting for round 1 and round 2 allocations
- [x] Make divider margins dynamic for standard 1366px and mobile resolutions
- [x] Move scroll button to footer
	- Update back-to-top button styling 
- [x] Make action button sizes uniform across all mobile resolutions

round2_fcfs
mobile_action_buttons
iphone678plus_animation_home
iphonex_animation_home
1366_animation_home
1920_animation_home
1920_home_padding
1366_home_padding
Mobile_round2fcfs
mobile_back_to_top_btn
desktop_back_to_top_btn

### CODE REVIEW

**Review by kbaldo — APPROVED** [review]
Amazing work!

**Review by harveyjavier — APPROVED** [review]
Crispy!

**Review by swengr-janan — CHANGES_REQUESTED** [review]
Mat, wag yun yung image na gamitin mo sa FCFS. Baka ma copyright tayo ni Binance haha

**Comment by mativanarquero** [comment]
> Mat, wag yun yung image na gamitin mo sa FCFS. Baka ma copyright tayo ni Binance haha

Ay wait hahaha my bad sir

**Comment by swengr-janan** [comment]
Sigi lang @mativanarquero

**Comment by harveyjavier** [comment]
> Mat, wag yun yung image na gamitin mo sa FCFS. Baka ma copyright tayo ni Binance haha

Su yellow? Iyo nanggad haha kaya pala bako din uniform sa website. Garo naliligaw na yellow submarine

**Comment by swengr-janan** [comment]
> > Mat, wag yun yung image na gamitin mo sa FCFS. Baka ma copyright tayo ni Binance haha
> 
> Su yellow? Iyo nanggad haha kaya pala bako din uniform sa website. Garo naliligaw na yellow submarine

Iyo baga harps haha. Temporary lang muna yan sa test repo pero kapag dgdi sa main repo dapat dae na isabay ta delicades.

**Comment by kbaldo** [comment]
oh darn that's right! haha

**Comment by mativanarquero** [comment]
> Mat, wag yun yung image na gamitin mo sa FCFS. Baka ma copyright tayo ni Binance haha

Replaced Round 2 FCFS image
replace_round2_image

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
