### PR TITLE
Update Timer Mobile Responsiveness and Update Swap Href

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Update project's countdown timer for mobile responsiveness
    - Update and isolate timer styling
    - Resolves: Fix mobile display of timer #74
    - Add dynamic support for mobile views with lower resolutions
- [x] Update Swap nav href
    - Resolves: Error in navbar links #73

swap_href_navbar
timer_mobile_resp

### CODE REVIEW

**Review by swengr-janan — APPROVED** [review]
Hrefed!

**Review by Pseudoman21 — APPROVED** [review]
Upgraded!

**Review by kbaldo — APPROVED** [review]
Up to date!

**Review by aldrickb — APPROVED** [review]
LGTTM

**Review by harveyjavier — APPROVED** [review]
Dynamic!

**Comment by harveyjavier** [comment]
Slow hands!

**Pull request merged**
