### PR TITLE
Update Formatting and Added Fixes

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Add 'Exclusive to binance' to header
    - Resolves: Add [Exclusive on Binance] #55
- [x] Rename 'Participate' to 'Staking'
- [x] Update formatting - About Titles"
    - Resolves: Center title #59
- [x] Update binance logo positioning
- [x] Update ownly project description
- [x] Add space: 'Remaining: ' - for currency input panel 
- [x] fix image formatting (PNG/JPG extensions) for deployment 
- [x] Update home - mobile responsivess for Iphone 6/6plus, 7/7plus, 8/8plus
- [x] Change from [Raised] -> [Raise] #60 
    - Revert 'Total Raise' to 'Total Raised' for Project and Launchcard

header_update
binance_reposition
iphone6-7-8-plus
iphone6-7-8

### CODE REVIEW

**Review by swengr-janan — CHANGES_REQUESTED** [review]
Change styling for [Exclusively on Binance Smart Chain]

**Comment by mativanarquero** [comment]
> Change styling for [Exclusively on Binance Smart Chain]

Updated sir.

**Comment by mativanarquero** [comment]
> Change styling for [Exclusively on Binance Smart Chain]

**Comment by harveyjavier** [comment]
Ba't mo pala @mativanarquero tig close earlier? Pag di pa ready ang PR, pweds man sya i-draft muna. Iba rin kasi ang close

**Comment by harveyjavier** [comment]
Or napindot lng? haha

**Comment by mativanarquero** [comment]
> Ba't mo pala @mativanarquero tig close earlier? Pag di pa ready ang PR, pweds man sya i-draft muna. Iba rin kasi ang close

Napindot po su 'close with comment' by accident hehe

**Review by swengr-janan — APPROVED** [review]

**Review by swengr-janan — APPROVED** [review]

**Pull request merged**
