### PR TITLE
Resolve Initial Issues

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Stake SRK earn typo
- [x] Update Launchpad Header: Ignite your token on SparkLaunch!
- [x] Update initial SocMeds  
- [x] Change [distrubute] -> [distribute] #11
- [x] Update latest staking requirements
- [x] Resolves: Change [Available] to [Remaining] #15  
- [x] Redo card container mapping with key
- [x] Resolves: Apply the latest Staking Requirement #7
- [x] Redo card container mapping with key

### CODE REVIEW

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Comment by kojiadrianojr** [comment]
GNYP

**Review by harveyjavier — APPROVED** [review]
Resolved!

**Comment by harveyjavier** [comment]
for AMD na mga orb?

**Comment by swengr-janan** [comment]
sige na harps

**Pull request merged**
