### PR TITLE
Modify the card and modal

### PR DESCRIPTION
**Pull request by kojiadrianojr**
Add sfuel to staking options
stakingcards

### CODE REVIEW

**Comment by harveyjavier** [comment]
Nice may SFUEL na. Apprubing..

**Review by mativanarquero — APPROVED** [review]

**Review by harveyjavier — APPROVED** [review]
SFUELed

**Review by Pseudoman21 — APPROVED** [review]
To the moon!

**Review by swengr-janan — CHANGES_REQUESTED** [review]
@kojiadrianojr , dapat naka disable si [Confirm] kapag 0 yung nasa slider or checkbox

**Comment by kojiadrianojr** [comment]
Updated: @swengr-janan 
stakingcards

**Review by swengr-janan — APPROVED** [review]
IN HOOD ALL THE GOODS!!

**Pull request merged**
