### PR TITLE
Add countdown timer (for integration)

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Supply "Contact Us" - mailto: support@sparkpoint.io
- [x] Supply appropriate OWNLY soc links
- [x] Add countdown timer (for integration)
      - src/pages/home/HeaderSection/timer.tsx
contact_us
home
timer

### CODE REVIEW

**Comment by harveyjavier** [comment]
Provide ka @mativanarquero screenshots or screenrecord gif via licecap

**Review by harveyjavier — APPROVED** [review]
Time's up!

**Review by kojiadrianojr — APPROVED** [review]
Countandified!

**Review by medardm — APPROVED** [review]
LGTM

**Pull request merged**
