### PR TITLE
Mobile responsiveness optimizations, purchase modal and project header icon updates

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Update arrow icon function for purchase modal
- [x] Remove home page horizontal scrolling
- [x] Mobile responsiveness - styled div margins
- [x] Update Ownly project headers
- [x] Mobile responsiveness - Projects: Card group
- [x] Update mobile responsive support for Iphone 6, 7, 8
- [x] Fix tier system list title alignment 
- [x] Add Description 3 for OWNLY Project component
- [x] Update Ownly descriptions
- [x] Adjust footer padding for mobile responsiveness

home
purchase modal arrow
cheader2
c_header
mobile_resp_iphone6-7-8
projects
Action_buttons_iphone6-7-8

### CODE REVIEW

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Review by clowreed — APPROVED** [review]
Responsive!

**Review by Pseudoman21 — APPROVED** [review]
Optimized!

**Review by kojiadrianojr — APPROVED** [review]

**Review by harveyjavier — APPROVED** [review]
Dynamic!

**Review by medardm — APPROVED** [review]
LGTM

**Pull request merged**
