### PR TITLE
Update linting rules

### PR DESCRIPTION
**Pull request by mativanarquero**
- [x] Update linting rule 
    - Allow .js extensions for JSX
lint

### CODE REVIEW

**Review by swengr-janan — APPROVED** [review]
Updated!

**Comment by kojiadrianojr** [comment]
fast hands

**Comment by kojiadrianojr** [comment]
bakit mo pig enable jsx?

**Comment by mativanarquero** [comment]
> bakit mo pig enable jsx?

.JS po sir implementation ko ng back-to-top button and header animation

**Comment by kojiadrianojr** [comment]
Di ba siya pwede sa tsx?

**Comment by mativanarquero** [comment]
> Di ba siya pwede sa tsx?

Pwede ko po sir imigrate yung functions and integration to typescript for future improvements.

**Pull request merged**
