### PR TITLE
Modify tier system list

### PR DESCRIPTION
**Pull request by mativanarquero**

### CODE REVIEW

**Review by harveyjavier — APPROVED** [review]
Modified!

**Review by swengr-janan — CHANGES_REQUESTED** [review]
Pachange ng requirement and poolWeight according to their respective allocation
image

**Comment by kojiadrianojr** [comment]
sa develop muna tayo mag PR @mativanarquero

**Comment by harveyjavier** [comment]
awts sa main ka pala @mativanarquero nag PR

**Comment by harveyjavier** [comment]
modified na @kojiadrianojr

**Comment by kojiadrianojr** [comment]
tinks

**Review by kojiadrianojr — APPROVED** [review]
Changified!

**Comment by harveyjavier** [comment]
> Pachange ng requirement and poolWeight according to their respective allocation
> image

accomplish mo muna @mativanarquero CR (change req.) ni balpz @swengr-janan

**Review by swengr-janan — CHANGES_REQUESTED** [review]
image

change pool weight, tapos paki ayos nalang din nung arrangement

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
