### PR TITLE
Issues/fix data

### PR DESCRIPTION
**Pull request by kojiadrianojr**
- [ ] Display remaining allocations
image

- [ ] Fix whitelist accounts case sensitivity matching
image

- [ ] Show notifications and error handling for purchase transaction
toasts

### CODE REVIEW

**Review by harveyjavier — APPROVED** [review]
Polished!

**Review by swengr-janan — CHANGES_REQUESTED** [review]
image

**Comment by kojiadrianojr** [comment]
Updated [ Purchase Modal ] 
image

**Review by medardm — APPROVED** [review]
LGTM!

**Review by aldrickb — APPROVED** [review]
LGTTM

**Review by swengr-janan — APPROVED** [review]
AGITH!

**Pull request merged**
